import type { VaultLeadCore } from "./vault-radar.types";

export function formatLeadMarkdown(lead: VaultLeadCore): string {
  const contactLines = [
    lead.contacts.twitter ? `- Twitter/X: ${lead.contacts.twitter}` : null,
    lead.contacts.discord ? `- Discord: ${lead.contacts.discord}` : null,
    lead.contacts.telegram ? `- Telegram: ${lead.contacts.telegram}` : null,
    lead.contacts.websites.length
      ? `- Web: ${lead.contacts.websites.join(", ")}`
      : null,
  ]
    .filter(Boolean)
    .join("\n");

  return `# Vault Risk Lead Report

**Target:** Vault ${lead.vaultName} (\`${lead.vaultAddress}\`)
**Leader:** \`${lead.leaderAddress}\`${lead.contacts.twitter ? ` · ${lead.contacts.twitter}` : ""}
**TVL:** $${lead.tvlUsd.toLocaleString(undefined, { maximumFractionDigits: 2 })}
**Risk Score:** ${lead.riskScore}/100

## Detected Vulnerability
**${lead.vulnerability}**

| Metric | Value |
|--------|-------|
| Day drawdown | $${lead.dayDrawdownUsd.toLocaleString()} |
| Week drawdown | $${lead.weekDrawdownUsd.toLocaleString()} |
| Trade frequency (day) | ${(lead.tradeFrequencyScore * 100).toFixed(0)}% |
| Depth mismatch ratio | ${lead.depthMismatchRatio}x |
| Est. slippage exposure | $${lead.estimatedSlippageExposureUsd.toLocaleString()} |
| **Est. loss saved by 500ms Fail-Closed** | **$${lead.estimatedLossSavedByFailClosedUsd.toLocaleString()} USD** |

## L2 Depth Probes
${lead.depthProbes
  .map(
    (p) =>
      `- **${p.coin}:** depth $${Math.round(p.depthUsd).toLocaleString()} · ${p.latencyMs}ms · fail-closed=${p.failClosedWouldTrip ? "TRIP" : "PASS"}`,
  )
  .join("\n")}

## Public Contact Points
${contactLines || "- No social links parsed from vault description"}

## Cold Outreach Hook
> ${lead.coldOutreachHook}

---
*Generated by SliverVine Vault Risk Radar · \`pnpm radar:report ${lead.vaultAddress}\`*
`;
}
